name: Loadmill Test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deployment:
    name: Run Load Tests
    runs-on: ubuntu-20.04
    env:
      LOADMILL_API_TOKEN: ${{ secrets.LOADMILL_API_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - id: set_var
        run: |
          content=`cat ./loadmill/config.json`
          # the following lines are only required for multi line json
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          # end of optional handling for multi line json
          echo "::set-output name=configJson::$content"
      - run: |
          echo "${{ steps.set_var.outputs.configJson }}"
      - name: Make Request
        id: myRequest
        uses: fjogeleit/http-request-action@master
        with:
          url: "https://www.loadmill.com/api/v1/tests"
          method: 'POST'
          bearerToken: ${{ secrets.LOADMILL_API_TOKEN }}
          data: ${{ steps.myRequest.outputs.response }}
      - name: Show Response
        run: echo ${{ steps.myRequest.outputs.response }}